#!/usr/bin/env python3
"""Build a FontAwesome *solid* subset limited to the icons actually used on the site.

Outputs (committed):
  docs/public/fonts/fa-solid-900-subset.woff2        — subset webfont (used glyphs only)
  docs/.vitepress/theme/fontawesome-core-subset.css  — fontawesome.css minus unused icon rules
  docs/.vitepress/theme/fontawesome-solid-subset.css — solid.css with @font-face -> subset font

Then theme/index.ts imports these two instead of the full @fortawesome CSS.
Re-run after adding/removing icons:  pyftsubset (fonttools) required.
"""
import re, os, sys, glob, subprocess

FA = "node_modules/@fortawesome/fontawesome-free"
core_css = open(f"{FA}/css/fontawesome.css", encoding="utf-8").read()
solid_css = open(f"{FA}/css/solid.css", encoding="utf-8").read()

# 1) icon -> codepoint, and the full text span of each single-icon block
block_re = re.compile(r'\.fa-([a-z0-9-]+)\s*\{[^{}]*?--fa:\s*"\\([0-9a-fA-F]+)"[^{}]*\}', re.S)
icon_cp = {}
for m in block_re.finditer(core_css):
    icon_cp.setdefault(m.group(1), m.group(2).lower())

# 2) icons actually used across the docs sources
used = set()
for ext in ("md", "ts", "mts", "vue", "js"):
    for f in glob.glob(f"docs/**/*.{ext}", recursive=True):
        try:
            for name in re.findall(r'fa-([a-z0-9-]+)', open(f, encoding="utf-8", errors="ignore").read()):
                used.add(name)
        except Exception:
            pass
icons = sorted(n for n in used if n in icon_cp)
cps = sorted({icon_cp[n] for n in icons})
print(f"icônes réelles utilisées : {len(icons)} | codepoints uniques : {len(cps)}")

# 3) subset the woff2
os.makedirs("docs/public/fonts", exist_ok=True)
src_font = f"{FA}/webfonts/fa-solid-900.woff2"
out_font = "docs/public/fonts/fa-solid-900-subset.woff2"
r = subprocess.run(["pyftsubset", src_font, f"--unicodes={','.join(cps)}",
                    "--flavor=woff2", "--layout-features=*", f"--output-file={out_font}"],
                   capture_output=True, text=True)
if r.returncode:
    print(r.stderr); sys.exit(1)
print(f"police : {os.path.getsize(src_font)/1024:.0f} KB -> {os.path.getsize(out_font)/1024:.0f} KB")

# 4) filter fontawesome.css: drop single-icon blocks whose name is unused
def drop(m):
    return "" if m.group(1) not in icons else m.group(0)
core_subset = block_re.sub(drop, core_css)
core_subset = re.sub(r'\n{3,}', '\n\n', core_subset)
open("docs/.vitepress/theme/fontawesome-core-subset.css", "w", encoding="utf-8").write(
    "/* Generated by scripts/build-fa-subset.py — fontawesome.css minus unused icon rules. */\n" + core_subset)
print(f"core CSS : {len(core_css)/1024:.0f} KB -> {len(core_subset)/1024:.0f} KB")

# 5) solid.css with @font-face src -> subset font
solid_subset = re.sub(r'src:\s*url\([^)]*\)\s*;',
                      'src: url("/fonts/fa-solid-900-subset.woff2") format("woff2");', solid_css)
open("docs/.vitepress/theme/fontawesome-solid-subset.css", "w", encoding="utf-8").write(
    "/* Generated by scripts/build-fa-subset.py — solid.css @font-face -> subset font. */\n" + solid_subset)
print("écrit : theme/fontawesome-core-subset.css + theme/fontawesome-solid-subset.css")
